=== AnatoliyVoit/git-projects/Exercises/CarRentXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="carRent" type="carRentType" />
	<xs:complexType name="orderType">
		<xs:sequence>
			<xs:element name="car">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Audi" />
						<xs:enumeration value="Ford" />
						<xs:enumeration value="Nissan" />
						<xs:enumeration value="Kia" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="model">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="A 100" />
						<xs:enumeration value="A4" />
						<xs:enumeration value="Mondeo" />
						<xs:enumeration value="X-trail" />
						<xs:enumeration value="Rio" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="totalAmount">
				<xs:simpleType>
					<xs:restriction base="xs:int"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="startDate">
				<xs:simpleType>
					<xs:restriction base="xs:string">
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="endDate">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute type="xs:string" name="number" use="optional" />
	</xs:complexType>
	<xs:complexType name="carRentType">
		<xs:sequence>
			<xs:element type="usersType" name="users" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="usersType">
		<xs:sequence>
			<xs:element type="userType" name="user" maxOccurs="unbounded"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="userType" mixed="true">
		<xs:sequence>
			<xs:element type="ordersType" name="orders" />
		</xs:sequence>
		<xs:attribute type="xs:int" name="id" use="optional" />
	</xs:complexType>
	<xs:complexType name="ordersType">
		<xs:sequence>
			<xs:element type="orderType" name="order" maxOccurs="unbounded"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== AnatoliyVoit/git-projects/Exercises/CarRent.xml
<?xml version="1.0" encoding="UTF-8"?>

<carRent xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="CarRentXMLSchema.xsd">
	<users>
		<user id="1">
			User1
			<orders>
				<order number="1">
					<car>Audi</car>
					<model>A 100</model>
					<totalAmount>150</totalAmount>
					<startDate>01.10.2015</startDate>
					<endDate>01.11.2015</endDate>
				</order>
				<order number="2">
					<car>Audi</car>
					<model>A4</model>
					<totalAmount>150</totalAmount>
					<startDate>14.10.2015</startDate>
					<endDate>01.12.2015</endDate>
				</order>
				<order number="3">
					<car>Ford</car>
					<model>Mondeo</model>
					<totalAmount>240</totalAmount>
					<startDate>11.11.2015</startDate>
					<endDate>18.12.2015</endDate>
				</order>
				<order number="4">
					<car>Nissan</car>
					<model>X-trail</model>
					<totalAmount>380</totalAmount>
					<startDate>11.01.2016</startDate>
					<endDate>23.02.2015</endDate>
				</order>
				<order number="5">
					<car>Kia</car>
					<model>Rio</model>
					<totalAmount>260</totalAmount>
					<startDate>02.03.2016</startDate>
					<endDate>18.05.2016</endDate>
				</order>
			</orders>
		</user>
		<user id="2">
			User2
			<orders>
				<order number="1">
					<car>Audi</car>
					<model>A 100</model>
					<totalAmount>150</totalAmount>
					<startDate>01.10.2015</startDate>
					<endDate>01.11.2015</endDate>
				</order>
				<order number="2">
					<car>Audi</car>
					<model>A4</model>
					<totalAmount>150</totalAmount>
					<startDate>14.10.2015</startDate>
					<endDate>01.12.2015</endDate>
				</order>
				<order number="3">
					<car>Ford</car>
					<model>Mondeo</model>
					<totalAmount>240</totalAmount>
					<startDate>11.11.2015</startDate>
					<endDate>18.12.2015</endDate>
				</order>
				<order number="4">
					<car>Nissan</car>
					<model>X-trail</model>
					<totalAmount>380</totalAmount>
					<startDate>11.01.2016</startDate>
					<endDate>23.02.2015</endDate>
				</order>
				<order number="5">
					<car>Kia</car>
					<model>Rio</model>
					<totalAmount>260</totalAmount>
					<startDate>02.03.2016</startDate>
					<endDate>18.05.2016</endDate>
				</order>
			</orders>
		</user>
		<user id="3">
			User3
			<orders>
				<order number="1">
					<car>Audi</car>
					<model>A 100</model>
					<totalAmount>150</totalAmount>
					<startDate>01.10.2015</startDate>
					<endDate>01.11.2015</endDate>
				</order>
				<order number="2">
					<car>Audi</car>
					<model>A4</model>
					<totalAmount>150</totalAmount>
					<startDate>14.10.2015</startDate>
					<endDate>01.12.2015</endDate>
				</order>
				<order number="3">
					<car>Ford</car>
					<model>Mondeo</model>
					<totalAmount>240</totalAmount>
					<startDate>11.11.2015</startDate>
					<endDate>18.12.2015</endDate>
				</order>
				<order number="4">
					<car>Nissan</car>
					<model>X-trail</model>
					<totalAmount>380</totalAmount>
					<startDate>11.01.2016</startDate>
					<endDate>23.02.2015</endDate>
				</order>
				<order number="5">
					<car>Kia</car>
					<model>Rio</model>
					<totalAmount>260</totalAmount>
					<startDate>02.03.2016</startDate>
					<endDate>18.05.2016</endDate>
				</order>
			</orders>
		</user>
		<user id="4">
			User4
			<orders>
				<order number="1">
					<car>Audi</car>
					<model>A 100</model>
					<totalAmount>150</totalAmount>
					<startDate>01.10.2015</startDate>
					<endDate>01.11.2015</endDate>
				</order>
				<order number="2">
					<car>Audi</car>
					<model>A4</model>
					<totalAmount>150</totalAmount>
					<startDate>14.10.2015</startDate>
					<endDate>01.12.2015</endDate>
				</order>
				<order number="3">
					<car>Ford</car>
					<model>Mondeo</model>
					<totalAmount>240</totalAmount>
					<startDate>11.11.2015</startDate>
					<endDate>18.12.2015</endDate>
				</order>
				<order number="4">
					<car>Nissan</car>
					<model>X-trail</model>
					<totalAmount>380</totalAmount>
					<startDate>11.01.2016</startDate>
					<endDate>23.02.2015</endDate>
				</order>
				<order number="5">
					<car>Kia</car>
					<model>Rio</model>
					<totalAmount>260</totalAmount>
					<startDate>02.03.2016</startDate>
					<endDate>18.05.2016</endDate>
				</order>
			</orders>
		</user>
		<user id="5">
			User5
			<orders>
				<order number="1">
					<car>Audi</car>
					<model>A 100</model>
					<totalAmount>150</totalAmount>
					<startDate>01.10.2015</startDate>
					<endDate>01.11.2015</endDate>
				</order>
				<order number="2">
					<car>Audi</car>
					<model>A4</model>
					<totalAmount>150</totalAmount>
					<startDate>14.10.2015</startDate>
					<endDate>01.12.2015</endDate>
				</order>
				<order number="3">
					<car>Ford</car>
					<model>Mondeo</model>
					<totalAmount>240</totalAmount>
					<startDate>11.11.2015</startDate>
					<endDate>18.12.2015</endDate>
				</order>
				<order number="4">
					<car>Nissan</car>
					<model>X-trail</model>
					<totalAmount>380</totalAmount>
					<startDate>11.01.2016</startDate>
					<endDate>23.02.2015</endDate>
				</order>
				<order number="5">
					<car>Kia</car>
					<model>Rio</model>
					<totalAmount>260</totalAmount>
					<startDate>02.03.2016</startDate>
					<endDate>18.05.2016</endDate>
				</order>
			</orders>
		</user>

	</users>
</carRent>
